version: '3'

services:
  backend:
    image: php-fpm
    volumes: 
      - ./backend
  frontend:
    image: nginx
    volumes: 
      - ./frontend/public

  db:
    image: mysql:5.7
    environment: 
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    volumes:
      - ./data/db

  redis:
    image: redis
    command: redis-server
    volumes:
      - ./data/redis

  
